### ISSUE TITLE
A compilation error when using more than three arguments/extractors in resource methods

### ISSUE THREAD

**Issue by manifest** [carllerche/tower-web#112] opened 2018-09-15 09:33 UTC
```rust
extern crate env_logger;
#[macro_use]
extern crate tower_web;

use tower_web::ServiceBuilder;

#[derive(Clone, Debug)]
struct Resource;

impl_web! {
    impl Resource {
        #[get("/:a/:b/:c/:d")]
        fn hello_world(&self, a: String, b: String, c: String, d: String) -> Result<String, ()> {
            Ok(format!("{}{}{}{}", a, b, c, d))
        }
    }
}

pub fn main() {
    env_logger::init();

    let addr = "0.0.0.0:8080".parse().expect("Invalid address");
    println!("Listening on http://{}", addr);

    ServiceBuilder::new()
        .resource(Resource)
        .run(&addr)
        .unwrap();
}
```

```rust
error[E0277]: the trait bound `tower_web::util::tuple::Join2<tower_web::extract::Immediate<std::string::String>, tower_web::extract::Immediate<std::string::String>>: tower_web::extract::ExtractFuture` is not satisfied
  --> src/main.rs:10:1
   |
10 | / impl_web! {
11 | |     impl Resource {
12 | |         #[get("/:a/:b/:c/:d")]
13 | |         fn hello_world(&self, a: String, b: String, c: String, d: String) -> Result<String, ()> {
...  |
16 | |     }
17 | | }
   | |_^ the trait `tower_web::extract::ExtractFuture` is not implemented for `tower_web::util::tuple::Join2<tower_web::extract::Immediate<std::string::String>, tower_web::extract::Immediate<std::string::String>>`
   |
   = note: required because of the requirements on the impl of `tower_web::codegen::futures::Future` for `tower_web::util::tuple::Join3<tower_web::util::tuple::Join2<tower_web::extract::Immediate<std::string::String>, tower_web::extract::Immediate<std::string::String>>, tower_web::extract::Immediate<std::string::String>, tower_web::extract::Immediate<std::string::String>>`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0599]: no method named `into_inner` found for type `tower_web::util::tuple::Join3<tower_web::util::tuple::Join2<tower_web::extract::Immediate<std::string::String>, tower_web::extract::Immediate<std::string::String>>, tower_web::extract::Immediate<std::string::String>, tower_web::extract::Immediate<std::string::String>>` in the current scope
  --> src/main.rs:10:1
   |
10 | / impl_web! {
11 | |     impl Resource {
12 | |         #[get("/:a/:b/:c/:d")]
13 | |         fn hello_world(&self, a: String, b: String, c: String, d: String) -> Result<String, ()> {
...  |
16 | |     }
17 | | }
   | |_^
   |
   = note: the method `into_inner` exists but the following trait bounds were not satisfied:
           `tower_web::util::tuple::Join2<tower_web::extract::Immediate<std::string::String>, tower_web::extract::Immediate<std::string::String>> : tower_web::extract::ExtractFuture`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0277]: the trait bound `tower_web::util::tuple::Join2<tower_web::extract::Immediate<std::string::String>, tower_web::extract::Immediate<std::string::String>>: tower_web::extract::ExtractFuture` is not satisfied
  --> src/main.rs:10:1
   |
10 | / impl_web! {
11 | |     impl Resource {
12 | |         #[get("/:a/:b/:c/:d")]
13 | |         fn hello_world(&self, a: String, b: String, c: String, d: String) -> Result<String, ()> {
...  |
16 | |     }
17 | | }
   | |_^ the trait `tower_web::extract::ExtractFuture` is not implemented for `tower_web::util::tuple::Join2<tower_web::extract::Immediate<std::string::String>, tower_web::extract::Immediate<std::string::String>>`
   |
   = note: required by `<tower_web::util::tuple::Join3<T0, T1, T2>>::new`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to 3 previous errors

Some errors occurred: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.
error: Could not compile `tower-ex`.

To learn more, run the command again with --verbose.
```

**Comment by shepmaster** [comment] 2018-09-15 16:43
Is this a duplicate of #106?

**Comment by manifest** [comment] 2018-09-15 17:41
I think so.

**Closed** 2018-09-15 17:41 UTC
